// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2XNCwUxNTofiVUfwA4FJVlfwD_h3i6R0',
    appId: '1:929976060924:web:ac9d9e1864750ca41f8079',
    messagingSenderId: '929976060924',
    projectId: 'segs-app',
    authDomain: 'segs-app.firebaseapp.com',
    storageBucket: 'segs-app.appspot.com',
    measurementId: 'G-F6ECSDX1VF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8NH2l5F8KWSxM8pswNYWmt4qW4EpUB3s',
    appId: '1:929976060924:android:9abfed128d820d351f8079',
    messagingSenderId: '929976060924',
    projectId: 'segs-app',
    storageBucket: 'segs-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZe9MUNqObdYQ3YhE1aIZjsEUFX5TyGdI',
    appId: '1:929976060924:ios:ccc9c8e89ef6bd1a1f8079',
    messagingSenderId: '929976060924',
    projectId: 'segs-app',
    storageBucket: 'segs-app.appspot.com',
    iosClientId: '929976060924-p2cs98d7hva6vciujjumcrnfev4nnq88.apps.googleusercontent.com',
    iosBundleId: 'com.example.segs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZe9MUNqObdYQ3YhE1aIZjsEUFX5TyGdI',
    appId: '1:929976060924:ios:ccc9c8e89ef6bd1a1f8079',
    messagingSenderId: '929976060924',
    projectId: 'segs-app',
    storageBucket: 'segs-app.appspot.com',
    iosClientId: '929976060924-p2cs98d7hva6vciujjumcrnfev4nnq88.apps.googleusercontent.com',
    iosBundleId: 'com.example.segs',
  );
}
